#! /bin/sh

# Setup Monitor Desktops
bspc monitor DVI-D-0 -d 1 2 3 4 # Asus
bspc monitor DVI-I-0 -d 5 6 7 8 # Gateway

bspc config split_ratio         0.50
bspc config border_width        2
bspc config window_gap          10
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

#Colors

bspc config focused_border_color "#31658c"
bspc config normal_border_color  "#141414"
bspc config focus_locked_border_color "#141414"
bspc config active_locked_border_color "#141414"
bspc config active_border_color "#141414"

panel &
