#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=20

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor="bar"

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
conky -c /home/mike/.conkyrc_bar > "$PANEL_FIFO" &

case "$flavor" in
	bar)
		cat "$PANEL_FIFO" | panel_bar | bar &
		;;
	dzen2)
		. panel_colors
		FONT_FAMILY='Lucida Console'
		FONT_SIZE=14
		cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
		;;
esac

wait