#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
	case $line in
		D*)
			sys_infos="\\br\\f7${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				focused="●"
				unfocused="●"
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos \\u6\\br\\f7${focused}\\ur"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos \\u4\\br\\fr${focused}\\ur"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos \\u9\\br\\fr${focused}\\ur"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos \\br\\f7${unfocused}"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos \\br\\fr${unfocused}"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos \\b1\\fr${unfocused}"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
						wm_infos="$wm_infos    \\br\\f2$layout"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "\\l $wm_infos \\r $sys_infos  "
done
