vim.g.mapleader = ','

require 'mthadley.options'
require 'mthadley.lspconfig'
require 'mthadley.gitsigns'
require 'mthadley.neoformat'
require 'mthadley.fugitive'
require 'mthadley.mappings'
require 'mthadley.cursorline'
require 'mthadley.filetype_quirks'
require 'mthadley.colors'
require 'mthadley.fzf'
