vim.g.mapleader = ','

require 'mthadley.options'
require 'mthadley.lspconfig'
require 'mthadley.gitsigns'
require 'mthadley.neoformat'
require 'mthadley.fugitive'
require 'mthadley.mappings'
require 'mthadley.cursorline'
require 'mthadley.filetype_quirks'
require 'mthadley.colors'
require 'mthadley.fzf'
require 'mthadley.vim_test'
require 'mthadley.vim_sort_motion'
require 'mthadley.netrw'
require 'mthadley.comment'
require 'mthadley.autopairs'
