on: push
name: Continuous Integration
jobs:
  test-setup:
    name: Test setup
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: run setup.sh
      run:
      - ./setup.sh
      # Running the script twice should succeed
      - ./setup.sh
    # GNU hello is installed by nix, validating that at least
    # _something_ got installed correctly.
    - name: check installation
      run: hello
