on:
  push:
  schedule:
    - cron: '0 0 * * SUN'
name: Continuous Integration
jobs:
  test-setup:
    name: Test setup
    strategy:
      matrix:
        os:
        # The MacOS installer now requires the "terminal" to be
        # restarted. Disabling the build until I can rework the
        # CI build to handle this.
        # - macos-latest
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      HOME_MANAGER_CONFIG: ci
    steps:
    - uses: actions/checkout@v2
    - name: run setup.sh
      run: ./setup.sh
    # Running the script twice should succeed
    - name: check setup.sh indempotence
      run: ./setup.sh
    # GNU hello is installed by nix, validating that at least
    # _something_ got installed correctly.
    - name: check installation
      run: |
        source ~/.nix-profile/etc/profile.d/nix.sh
        hello
